CREATE TABLE [Enrollment].[AccountMessageTopic]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [AccountId] UNIQUEIDENTIFIER NOT NULL, 
    [EnrollmentId] UNIQUEIDENTIFIER NULL, 
    [TopicId] UNIQUEIDENTIFIER NOT NULL, 
    [SubTopicId] UNIQUEIDENTIFIER NOT NULL
)
