trigger:
  - main  

variables:
  - group: DatabaseCredentials

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      npm init -y
      npm install @faker-js/faker mssql @azure/identity
    displayName: 'Install dependencies'
    workingDirectory: terraform/modules/api-enrollment/CFIK12.Database/DB_Hydration

  - script: |
      node terraform/modules/api-enrollment/CFIK12.Database/DB_Hydration/generate.mjs
    displayName: 'Run Faker Script and Insert Data into Azure SQL'
    env:
      DB_SERVER: $(DB_SERVER)
      DB_NAME: $(DB_NAME)

