trigger:
  - main  

variables:
  - group: DatabaseCredentials

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: dbSeed
    displayName: Seed Azure SQL with Faker Data
    timeoutInMinutes: 10
    uses: azure-pipelines-job
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: k12-development  
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            npm install @faker-js/faker mssql @azure/identity@latest
            node terraform/modules/api-enrollment/CFIK12.Database/DB_Hydration/generate.mjs
        env:
          DB_SERVER: $(DB_SERVER)
          DB_NAME: $(DB_NAME)
          AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
          AZURE_TENANT_ID: $(AZURE_TENANT_ID)
          AZURE_FEDERATED_TOKEN_FILE: /var/run/secrets/azure/tokens/azure-identity-token
        workingDirectory: terraform/modules/api-enrollment/CFIK12.Database/DB_Hydration
