apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: blobstorage
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: "{your-storage-account}"
  - name: accountKey
    secretKeyRef:
      name: azure-storage
      key: account-key
  - name: containerName
    value: "architecture-docs"
  - name: decodeBase64
    value: "false"
  - name: publicAccessLevel
    value: "none"
