apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cosmosdb-state
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: "https://{your-cosmosdb-account}.documents.azure.com:443/"
  - name: masterKey
    secretKeyRef:
      name: cosmosdb-credentials
      key: master-key
  - name: database
    value: "k12-architecture"
  - name: collection
    value: "statestore"
  - name: actorStateStore
    value: "true"
