apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    samplingRate: "1"
    stdout: true
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metric:
    enabled: true
  mtls:
    enabled: false
    workloadCertTTL: "24h"
    allowedClockSkew: "15m"
  secrets:
    scopes:
      - storeName: keyvault-secrets
        defaultAccess: allow
  accessControl:
    defaultAction: allow
    trustDomain: "public"
  api:
    allowed:
      - name: state
        version: v1
        protocol: http
      - name: pubsub
        version: v1
        protocol: http
      - name: bindings
        version: v1
        protocol: http
      - name: secrets
        version: v1
        protocol: http
      - name: invoke
        version: v1
        protocol: grpc
      - name: actors
        version: v1
        protocol: http
      - name: workflows
        version: v1alpha1
        protocol: http
  nameResolution:
    component: "mdns"
    version: "v1"
    configuration:
      selfRegister: true
