apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: keyvault-secrets
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "{your-keyvault-name}"
  - name: azureClientId
    value: "{your-client-id}"
  - name: azureClientSecret
    secretKeyRef:
      name: azure-credentials
      key: client-secret
  - name: azureTenantId
    value: "{your-tenant-id}"
