apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azureservicebus
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
  - name: namespaceName
    value: "{your-servicebus-namespace}.servicebus.windows.net"
  - name: connectionString
    secretKeyRef:
      name: servicebus-connectionstring
      key: connectionstring
  - name: consumerID
    value: "docs-api"
  - name: enableEntityManagement
    value: "true"
scopes:
  - docs-api
