#!/usr/bin/env python3
"""
Convert Aspire deployment manifest to Terraform for Azure Container Apps.

This script translates an Aspire manifest.json generated by 'azd infra synth'
into Terraform configuration files for Azure Container Apps deployment.

Usage:
    python manifest-to-terraform.py --manifest ./manifest/manifest.json --output ./terraform

Requirements:
    - Python 3.8+
    - jinja2
    - pyyaml
"""
import json
import argparse
from pathlib import Path
from typing import Dict, Any, List


def load_manifest(manifest_path: str) -> Dict[str, Any]:
    """Load and parse Aspire manifest JSON."""
    with open(manifest_path, 'r') as f:
        return json.load(f)


def generate_provider_config() -> str:
    """Generate Terraform provider configuration."""
    return '''terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}
'''


def generate_log_analytics() -> str:
    """Generate Log Analytics Workspace resource."""
    return '''# Log Analytics Workspace
resource "azurerm_log_analytics_workspace" "k12" {
  name                = "k12-docs-logs-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  sku                 = "PerGB2018"
  retention_in_days   = 30

  tags = var.common_tags
}
'''


def generate_app_insights(log_analytics_ref: str) -> str:
    """Generate Application Insights resource."""
    return '''# Application Insights
resource "azurerm_application_insights" "k12" {
  name                = "k12-docs-insights-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  application_type    = "web"
  workspace_id        = azurerm_log_analytics_workspace.k12.id

  tags = var.common_tags
}
'''


def generate_container_app_environment() -> str:
    """Generate Container Apps Environment resource."""
    return '''# Container Apps Environment
resource "azurerm_container_app_environment" "k12" {
  name                = "k12-docs-env-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location

  log_analytics_workspace_id              = azurerm_log_analytics_workspace.k12.id
  dapr_application_insights_connection_string = azurerm_application_insights.k12.connection_string

  tags = var.common_tags
}
'''


def generate_docs_api_container_app() -> str:
    """Generate Docs API Container App resource."""
    return '''# Container App: Docs API
resource "azurerm_container_app" "docs_api" {
  name                         = "k12-docs-api-${var.environment}"
  resource_group_name          = var.resource_group_name
  container_app_environment_id = azurerm_container_app_environment.k12.id
  revision_mode                = "Single"

  template {
    container {
      name   = "docs-api"
      image  = "${var.container_registry_url}/docs-api:${var.image_tag}"
      cpu    = "0.25"
      memory = "0.5Gi"

      env {
        name  = "ASPNETCORE_ENVIRONMENT"
        value = var.environment
      }
    }

    min_replicas = var.docs_api_min_replicas
    max_replicas = var.docs_api_max_replicas
  }

  dapr {
    app_id       = "docs-api"
    app_port     = 8080
    app_protocol = "http"
  }

  ingress {
    external_enabled = true
    target_port      = 8080
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }

  tags = var.common_tags

  depends_on = [
    azurerm_container_app_environment.k12
  ]
}
'''


def generate_docs_site_container_app() -> str:
    """Generate Docs Site Container App resource."""
    return '''# Container App: Angular Docs Site
resource "azurerm_container_app" "docs_site" {
  name                         = "k12-docs-site-${var.environment}"
  resource_group_name          = var.resource_group_name
  container_app_environment_id = azurerm_container_app_environment.k12.id
  revision_mode                = "Single"

  template {
    container {
      name   = "docs-site"
      image  = "${var.container_registry_url}/docs-site:${var.image_tag}"
      cpu    = "0.5"
      memory = "1.0Gi"

      env {
        name  = "NODE_ENV"
        value = var.environment
      }
    }

    min_replicas = var.docs_site_min_replicas
    max_replicas = var.docs_site_max_replicas
  }

  ingress {
    external_enabled = true
    target_port      = 3000
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }

  tags = var.common_tags

  depends_on = [
    azurerm_container_app_environment.k12
  ]
}
'''


def generate_outputs() -> str:
    """Generate outputs.tf file."""
    return '''output "container_app_environment_id" {
  description = "ID of the Container App Environment"
  value       = azurerm_container_app_environment.k12.id
}

output "docs_api_fqdn" {
  description = "FQDN of the Docs API Container App"
  value       = azurerm_container_app.docs_api.ingress[0].fqdn
}

output "docs_api_url" {
  description = "URL of the Docs API Container App"
  value       = "https://${azurerm_container_app.docs_api.ingress[0].fqdn}"
}

output "docs_site_fqdn" {
  description = "FQDN of the Docs Site Container App"
  value       = azurerm_container_app.docs_site.ingress[0].fqdn
}

output "docs_site_url" {
  description = "URL of the Docs Site Container App"
  value       = "https://${azurerm_container_app.docs_site.ingress[0].fqdn}"
}

output "log_analytics_workspace_id" {
  description = "ID of the Log Analytics Workspace"
  value       = azurerm_log_analytics_workspace.k12.id
}

output "app_insights_instrumentation_key" {
  description = "Instrumentation Key for Application Insights"
  value       = azurerm_application_insights.k12.instrumentation_key
  sensitive   = true
}

output "dashboard_url" {
  description = "Azure Portal dashboard URL for Container Apps Environment"
  value       = "https://portal.azure.com/#resource${azurerm_container_app_environment.k12.id}"
}
'''


def generate_variables() -> str:
    """Generate variables.tf file."""
    return '''variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be one of: dev, staging, prod."
  }
}

variable "resource_group_name" {
  description = "Name of the Azure resource group"
  type        = string
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "eastus"
}

variable "container_registry_url" {
  description = "URL of the container registry (e.g., myacr.azurecr.io)"
  type        = string
}

variable "image_tag" {
  description = "Tag/version of container images to deploy"
  type        = string
  default     = "latest"
}

variable "docs_api_min_replicas" {
  description = "Minimum number of replicas for Docs API"
  type        = number
  default     = 1

  validation {
    condition     = var.docs_api_min_replicas >= 0
    error_message = "Min replicas must be >= 0."
  }
}

variable "docs_api_max_replicas" {
  description = "Maximum number of replicas for Docs API"
  type        = number
  default     = 10

  validation {
    condition     = var.docs_api_max_replicas >= 1
    error_message = "Max replicas must be >= 1."
  }
}

variable "docs_site_min_replicas" {
  description = "Minimum number of replicas for Docs Site"
  type        = number
  default     = 1

  validation {
    condition     = var.docs_site_min_replicas >= 0
    error_message = "Min replicas must be >= 0."
  }
}

variable "docs_site_max_replicas" {
  description = "Maximum number of replicas for Docs Site"
  type        = number
  default     = 5

  validation {
    condition     = var.docs_site_max_replicas >= 1
    error_message = "Max replicas must be >= 1."
  }
}

variable "common_tags" {
  description = "Common tags to apply to all resources"
  type        = map(string)
  default = {
    Environment = "k12"
    ManagedBy   = "Terraform"
    Project     = "K12-Docs"
  }
}
'''


def generate_terraform_files(manifest: Dict[str, Any], output_dir: str) -> None:
    """Generate all Terraform files from Aspire manifest."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Generate main.tf
    main_tf_content = (
        generate_provider_config()
        + "\n\n"
        + generate_log_analytics()
        + "\n\n"
        + generate_app_insights("")
        + "\n\n"
        + generate_container_app_environment()
        + "\n\n"
        + generate_docs_api_container_app()
        + "\n\n"
        + generate_docs_site_container_app()
    )

    with open(output_path / "main.tf", "w") as f:
        f.write(main_tf_content)

    # Generate variables.tf
    with open(output_path / "variables.tf", "w") as f:
        f.write(generate_variables())

    # Generate outputs.tf
    with open(output_path / "outputs.tf", "w") as f:
        f.write(generate_outputs())

    # Generate terraform.tfvars.example
    tfvars_example = '''environment              = "dev"
resource_group_name     = "k12-dev-rg"
location                = "eastus"
container_registry_url  = "k12acr.azurecr.io"
image_tag               = "latest"
docs_api_min_replicas   = 1
docs_api_max_replicas   = 10
docs_site_min_replicas  = 1
docs_site_max_replicas  = 5

common_tags = {
  Environment = "k12-dev"
  ManagedBy   = "Terraform"
  Project     = "K12-Docs"
  CostCenter  = "Engineering"
}
'''
    with open(output_path / "terraform.tfvars.example", "w") as f:
        f.write(tfvars_example)

    print(f"✅ Terraform files generated successfully in {output_dir}")
    print(f"   - main.tf (resources)")
    print(f"   - variables.tf (input variables)")
    print(f"   - outputs.tf (output values)")
    print(f"   - terraform.tfvars.example (example values file)")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Convert Aspire deployment manifest to Terraform",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python manifest-to-terraform.py --manifest ./manifest.json --output ./terraform
  python manifest-to-terraform.py \\
    --manifest infra/manifest/manifest.json \\
    --output infra/terraform
        """,
    )

    parser.add_argument(
        "--manifest",
        required=True,
        help="Path to Aspire manifest.json",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output directory for Terraform files",
    )

    args = parser.parse_args()

    try:
        manifest = load_manifest(args.manifest)
        generate_terraform_files(manifest, args.output)
        print("\n✅ Terraform generation completed successfully!")
    except FileNotFoundError:
        print(f"❌ Error: Manifest file not found: {args.manifest}")
        exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Error: Invalid JSON in manifest: {e}")
        exit(1)
    except Exception as e:
        print(f"❌ Error: {e}")
        exit(1)


if __name__ == "__main__":
    main()
