#!/usr/bin/env python3
"""
Convert Aspire deployment manifest to Bicep for Azure Container Apps.

This script translates an Aspire manifest.json generated by 'azd infra synth'
into Bicep template files for Azure Container Apps deployment.

Usage:
    python manifest-to-bicep.py --manifest ./manifest/manifest.json --output ./bicep

Requirements:
    - Python 3.8+
    - pyyaml
    - jinja2 (optional, for advanced templating)
"""
import json
import argparse
from pathlib import Path
from typing import Dict, Any


def load_manifest(manifest_path: str) -> Dict[str, Any]:
    """Load and parse Aspire manifest JSON."""
    with open(manifest_path, 'r') as f:
        return json.load(f)


def generate_main_bicep() -> str:
    """Generate main.bicep template."""
    return '''@description('Environment name (dev, staging, prod)')
param environment string

@description('Azure region')
param location string = resourceGroup().location

@description('Container Apps Environment name')
param containerAppEnvName string = 'k12-docs-env-${environment}'

@description('Log Analytics Workspace name')
param logAnalyticsName string = 'k12-docs-logs-${environment}'

@description('Application Insights name')
param appInsightsName string = 'k12-docs-insights-${environment}'

@description('Container Registry URL')
param containerRegistryUrl string

@description('Container image tag')
param imageTag string = 'latest'

@description('Docs API minimum replicas')
param docsApiMinReplicas int = 1

@description('Docs API maximum replicas')
param docsApiMaxReplicas int = 10

@description('Docs Site minimum replicas')
param docsSiteMinReplicas int = 1

@description('Docs Site maximum replicas')
param docsSiteMaxReplicas int = 5

@description('Common tags for all resources')
param commonTags object = {
  Environment: environment
  ManagedBy: 'Bicep'
  Project: 'K12-Docs'
}

// Variables
var logAnalyticsWorkspaceName = logAnalyticsName
var appInsightsName_var = appInsightsName
var containerAppEnvName_var = containerAppEnvName
var docsApiName = 'k12-docs-api-${environment}'
var docsSiteName = 'k12-docs-site-${environment}'

// ===========================
// Log Analytics Workspace
// ===========================
resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsWorkspaceName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
  }
  tags: commonTags
}

// ===========================
// Application Insights
// ===========================
resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName_var
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalyticsWorkspace.id
    RetentionInDays: 30
  }
  tags: commonTags
}

// ===========================
// Container Apps Environment
// ===========================
resource containerAppEnvironment 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: containerAppEnvName_var
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalyticsWorkspace.properties.customerId
        sharedKey: logAnalyticsWorkspace.listKeys().primarySharedKey
      }
    }
    daprAIConnectionString: applicationInsights.properties.ConnectionString
    infrastructureSubnetId: ''
    internal: false
    zoneRedundant: false
  }
  tags: commonTags
}

// ===========================
// Docs API Container App
// ===========================
resource docsApiContainerApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: docsApiName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    managedEnvironmentId: containerAppEnvironment.id
    environmentId: containerAppEnvironment.id
    configuration: {
      dapr: {
        enabled: true
        appId: 'docs-api'
        appPort: 8080
        appProtocol: 'http'
      }
      ingress: {
        external: true
        targetPort: 8080
        exposedPort: 0
        transport: 'auto'
        traffic: [
          {
            weight: 100
            latestRevision: true
          }
        ]
        allowInsecure: false
      }
      secrets: []
      registries: [
        {
          server: containerRegistryUrl
          username: ''
          passwordSecretRef: ''
        }
      ]
    }
    template: {
      revisionSuffix: 'v1'
      containers: [
        {
          name: 'docs-api'
          image: '${containerRegistryUrl}/docs-api:${imageTag}'
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
          env: [
            {
              name: 'ASPNETCORE_ENVIRONMENT'
              value: environment
            }
          ]
          probes: [
            {
              type: 'liveness'
              httpGet: {
                path: '/health'
                port: 8080
                scheme: 'HTTP'
              }
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
            }
            {
              type: 'readiness'
              httpGet: {
                path: '/health/ready'
                port: 8080
                scheme: 'HTTP'
              }
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 2
            }
          ]
        }
      ]
      scale: {
        minReplicas: docsApiMinReplicas
        maxReplicas: docsApiMaxReplicas
        rules: [
          {
            name: 'http-scaling'
            http: {
              metadata: {
                concurrentRequests: '10'
              }
            }
          }
        ]
      }
    }
  }
  tags: commonTags
  dependsOn: [
    containerAppEnvironment
  ]
}

// ===========================
// Docs Site Container App
// ===========================
resource docsSiteContainerApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: docsSiteName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    managedEnvironmentId: containerAppEnvironment.id
    environmentId: containerAppEnvironment.id
    configuration: {
      ingress: {
        external: true
        targetPort: 3000
        exposedPort: 0
        transport: 'auto'
        traffic: [
          {
            weight: 100
            latestRevision: true
          }
        ]
        allowInsecure: false
      }
      secrets: []
      registries: [
        {
          server: containerRegistryUrl
          username: ''
          passwordSecretRef: ''
        }
      ]
    }
    template: {
      revisionSuffix: 'v1'
      containers: [
        {
          name: 'docs-site'
          image: '${containerRegistryUrl}/docs-site:${imageTag}'
          resources: {
            cpu: json('0.5')
            memory: '1.0Gi'
          }
          env: [
            {
              name: 'NODE_ENV'
              value: environment
            }
          ]
          probes: [
            {
              type: 'liveness'
              httpGet: {
                path: '/'
                port: 3000
                scheme: 'HTTP'
              }
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
            }
            {
              type: 'readiness'
              httpGet: {
                path: '/'
                port: 3000
                scheme: 'HTTP'
              }
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 2
            }
          ]
        }
      ]
      scale: {
        minReplicas: docsSiteMinReplicas
        maxReplicas: docsSiteMaxReplicas
      }
    }
  }
  tags: commonTags
  dependsOn: [
    containerAppEnvironment
  ]
}

// ===========================
// Outputs
// ===========================
@description('Container App Environment ID')
output containerAppEnvironmentId string = containerAppEnvironment.id

@description('Container App Environment Name')
output containerAppEnvironmentName string = containerAppEnvironment.name

@description('Docs API FQDN')
output docsApiFqdn string = docsApiContainerApp.properties.configuration.ingress.fqdn

@description('Docs API URL')
output docsApiUrl string = 'https://${docsApiContainerApp.properties.configuration.ingress.fqdn}'

@description('Docs Site FQDN')
output docsSiteFqdn string = docsSiteContainerApp.properties.configuration.ingress.fqdn

@description('Docs Site URL')
output docsSiteUrl string = 'https://${docsSiteContainerApp.properties.configuration.ingress.fqdn}'

@description('Log Analytics Workspace ID')
output logAnalyticsWorkspaceId string = logAnalyticsWorkspace.id

@description('Application Insights Instrumentation Key')
@secure()
output appInsightsInstrumentationKey string = applicationInsights.properties.InstrumentationKey

@description('Application Insights Connection String')
@secure()
output appInsightsConnectionString string = applicationInsights.properties.ConnectionString

@description('Azure Portal Dashboard URL')
output dashboardUrl string = 'https://portal.azure.com/#resource${containerAppEnvironment.id}'
'''


def generate_parameters_bicep() -> str:
    """Generate parameters.bicep file."""
    return '''using './main.bicep'

param environment = 'dev'
param location = 'eastus'
param containerAppEnvName = 'k12-docs-env-dev'
param logAnalyticsName = 'k12-docs-logs-dev'
param appInsightsName = 'k12-docs-insights-dev'
param containerRegistryUrl = 'k12acr.azurecr.io'
param imageTag = 'latest'
param docsApiMinReplicas = 1
param docsApiMaxReplicas = 10
param docsSiteMinReplicas = 1
param docsSiteMaxReplicas = 5
param commonTags = {
  Environment: 'dev'
  ManagedBy: 'Bicep'
  Project: 'K12-Docs'
  CostCenter: 'Engineering'
}
'''


def generate_bicep_files(manifest: Dict[str, Any], output_dir: str) -> None:
    """Generate all Bicep files from Aspire manifest."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Generate main.bicep
    with open(output_path / "main.bicep", "w") as f:
        f.write(generate_main_bicep())

    # Generate parameters.bicep
    with open(output_path / "parameters.bicep", "w") as f:
        f.write(generate_parameters_bicep())

    # Generate bicepparam example files
    dev_params = '''using './main.bicep'

param environment = 'dev'
param location = 'eastus'
param containerAppEnvName = 'k12-docs-env-dev'
param logAnalyticsName = 'k12-docs-logs-dev'
param appInsightsName = 'k12-docs-insights-dev'
param containerRegistryUrl = 'k12acr.azurecr.io'
param imageTag = 'dev-latest'
param docsApiMinReplicas = 1
param docsApiMaxReplicas = 5
param docsSiteMinReplicas = 1
param docsSiteMaxReplicas = 3
param commonTags = {
  Environment: 'dev'
  ManagedBy: 'Bicep'
  Project: 'K12-Docs'
  CostCenter: 'Engineering'
  Stack: 'Development'
}
'''
    with open(output_path / "main.dev.bicepparam", "w") as f:
        f.write(dev_params)

    staging_params = '''using './main.bicep'

param environment = 'staging'
param location = 'eastus'
param containerAppEnvName = 'k12-docs-env-staging'
param logAnalyticsName = 'k12-docs-logs-staging'
param appInsightsName = 'k12-docs-insights-staging'
param containerRegistryUrl = 'k12acr.azurecr.io'
param imageTag = 'staging-latest'
param docsApiMinReplicas = 2
param docsApiMaxReplicas = 10
param docsSiteMinReplicas = 2
param docsSiteMaxReplicas = 5
param commonTags = {
  Environment: 'staging'
  ManagedBy: 'Bicep'
  Project: 'K12-Docs'
  CostCenter: 'Engineering'
  Stack: 'Staging'
}
'''
    with open(output_path / "main.staging.bicepparam", "w") as f:
        f.write(staging_params)

    prod_params = '''using './main.bicep'

param environment = 'prod'
param location = 'eastus'
param containerAppEnvName = 'k12-docs-env-prod'
param logAnalyticsName = 'k12-docs-logs-prod'
param appInsightsName = 'k12-docs-insights-prod'
param containerRegistryUrl = 'k12acr.azurecr.io'
param imageTag = 'v1.0'
param docsApiMinReplicas = 3
param docsApiMaxReplicas = 20
param docsSiteMinReplicas = 3
param docsSiteMaxReplicas = 10
param commonTags = {
  Environment: 'prod'
  ManagedBy: 'Bicep'
  Project: 'K12-Docs'
  CostCenter: 'Operations'
  Stack: 'Production'
  Compliance: 'FedRAMP'
}
'''
    with open(output_path / "main.prod.bicepparam", "w") as f:
        f.write(prod_params)

    print(f"✅ Bicep files generated successfully in {output_dir}")
    print(f"   - main.bicep (template)")
    print(f"   - parameters.bicep (default parameters)")
    print(f"   - main.dev.bicepparam (dev environment)")
    print(f"   - main.staging.bicepparam (staging environment)")
    print(f"   - main.prod.bicepparam (prod environment)")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Convert Aspire deployment manifest to Bicep",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python manifest-to-bicep.py --manifest ./manifest.json --output ./bicep
  python manifest-to-bicep.py \\
    --manifest infra/manifest/manifest.json \\
    --output infra/bicep
        """,
    )

    parser.add_argument(
        "--manifest",
        required=True,
        help="Path to Aspire manifest.json",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output directory for Bicep files",
    )

    args = parser.parse_args()

    try:
        manifest = load_manifest(args.manifest)
        generate_bicep_files(manifest, args.output)
        print("\n✅ Bicep generation completed successfully!")
    except FileNotFoundError:
        print(f"❌ Error: Manifest file not found: {args.manifest}")
        exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Error: Invalid JSON in manifest: {e}")
        exit(1)
    except Exception as e:
        print(f"❌ Error: {e}")
        exit(1)


if __name__ == "__main__":
    main()
